[package]
name = "hanako-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Rocket Webserver
rocket = "0.5.0-rc.1"

# storing database connection user and password in a file
dotenv = "0.15.0"
